# Docker Composeのバージョンを指定
version: '3'

services:
  # ROS2デスクトップ環境のサービス定義
  ros2-desktop:
    # カスタムDockerfileからビルド
    build: .
    
    # ポート転送の設定
    ports:
      - "6080:80"     # noVNC (ブラウザベースVNC) 用ポート
      - "10000:10000" # 通常のVNCクライアント用ポート
    
    # ボリュームマウントの設定
    volumes:
      # ホストのws_colconディレクトリをコンテナ内のws_colconにマウント
      # cached: パフォーマンス向上のためのキャッシュオプション
      - ./ws_colcon:/home/ubuntu/ws_colcon:cached
    
    # 共有メモリサイズの設定(GUIアプリケーションのパフォーマンス向上用)
    shm_size: '1024m'
