joint_limits:
  joint1:
    has_position_limits: true
    min_position: -2.356
    max_position: 2.356
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
  joint2:
    has_position_limits: true
    min_position: -2.356
    max_position: 2.356
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  joint3:
    has_position_limits: true
    min_position: -2.356
    max_position: 2.356
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  joint4:
    has_position_limits: true
    min_position: -2.356
    max_position: 2.356
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  joint5:
    has_position_limits: true
    min_position: -1.571
    max_position: 1.571
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
